name: shree_vimal_mobile_dhule
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  mysql_client: ^0.0.27
  google_fonts: ^6.2.1
  fluent_ui: 4.7.7
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  icons_launcher: ^2.1.7
  device_preview: ^1.1.0
  shared_preferences: ^2.0.20  
  update_handler: ^0.0.9
  package_info_plus: 
  another_flushbar:
  pwa_update_listener: ^0.1.0
  image_picker: ^1.1.2
  excel: ^4.0.3
  open_filex: ^4.4.0
  pdf: ^3.11.0
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  printing: ^5.13.1
  flutter_barcode_scanner: ^2.0.0
  indian_currency_to_word: ^1.0.0
  # internet_file: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/